import { enviarTelegram } from "../services/telegram.js";
import { atualizarPainel } from "../services/panel.js";
import { listarGrupos } from "../services/groups.js";

export async function handleDisparoCallback(env, callback) {
  const data=callback.data,chatId=callback.message.chat.id,userId=callback.from.id.toString(),key=`state_${userId}`;
  if(data==="disparo:cancelar"){const raw=await env.KV_BOT_BANNERS.get(key);if(raw)try{const s=JSON.parse(raw);await apagarPrevia(env,chatId,s);await apagarMensagem(env,chatId,s.confirmMessageId)}catch{}await env.KV_BOT_BANNERS.delete(key);await apagarMensagem(env,chatId,callback.message.message_id);return enviarTelegram(env.TELEGRAM_TOKEN,"sendMessage",{chat_id:chatId,text:"❌ <b>Disparo cancelado.</b>\n\nNenhuma mensagem foi enviada.",parse_mode:"HTML",reply_markup:{inline_keyboard:[[{text:"🏠 Voltar ao Painel",callback_data:"menu:inicio"}]]}})}
  const raw=await env.KV_BOT_BANNERS.get(key);if(!raw)return estadoExpirado(env,callback);const state=JSON.parse(raw);state.userId=userId;state.panelMessageId??=callback.message.message_id;
  if(data==="disparo:legenda"){state.step="WAITING_CAPTION";await salvarEstado(env,key,state);return atualizarPainel(env,chatId,state.panelMessageId,"📝 <b>ADICIONAR LEGENDA</b>\n\nEnvie agora o texto que deseja usar como legenda da mídia.",[[{text:"❌ Cancelar",callback_data:"disparo:cancelar"}]])}
  if(data==="disparo:sem_legenda"){state.step="WAITING_BUTTON_CHOICE";await salvarEstado(env,key,state);return atualizarPainel(env,chatId,state.panelMessageId,"✅ <b>SEM LEGENDA</b>\n\nDeseja adicionar botões à publicação?",[[{text:"🔘 Adicionar Botões",callback_data:"disparo:botoes"}],[{text:"➡️ Continuar sem Botões",callback_data:"disparo:sem_botoes"}],[{text:"❌ Cancelar",callback_data:"disparo:cancelar"}]])}
  if(data==="disparo:botoes"){state.step="WAITING_BUTTONS_INPUT";await salvarEstado(env,key,state);return atualizarPainel(env,chatId,state.panelMessageId,"🔘 <b>ADICIONAR BOTÕES</b>\n\nEnvie:\n<code>Comprar - https://site.com</code>\n\nEm álbum, os botões ficam logo abaixo.",[[{text:"❌ Cancelar",callback_data:"disparo:cancelar"}]])}
  if(data==="disparo:sem_botoes"){state.buttons=null;return oferecerFixacao(env,chatId,state,key,callback.message.message_id)}
  if(data==="disparo:fixar"){state.fixar=true;state.step="WAITING_CONFIRMATION";await apagarMensagem(env,chatId,callback.message.message_id);state.panelMessageId=null;await salvarEstado(env,key,state);return mostrarConfirmacao(env,chatId,state)}
  if(data==="disparo:nao_fixar"){state.fixar=false;state.step="WAITING_CONFIRMATION";await apagarMensagem(env,chatId,callback.message.message_id);state.panelMessageId=null;await salvarEstado(env,key,state);return mostrarConfirmacao(env,chatId,state)}
  if(data==="disparo:confirmar"){if(state.sending)return;state.sending=true;await salvarEstado(env,key,state);await apagarPrevia(env,chatId,state);await apagarMensagem(env,chatId,state.confirmMessageId||callback.message.message_id);const grupos=await listarGrupos(env),status=await enviarTelegram(env.TELEGRAM_TOKEN,"sendMessage",{chat_id:chatId,text:`🚀 <b>Iniciando disparo...</b>\n\n📡 Destinos: <b>${grupos.length}</b> grupos\n📌 Fixar: <b>${state.fixar?"SIM":"NÃO"}</b>`,parse_mode:"HTML"});let sucessos=0,erros=0,fixados=0,errosFixacao=0;const markup=state.buttons?{inline_keyboard:state.buttons}:undefined;for(const id of grupos){try{const enviado=await enviarConteudo(env,id,state,markup);sucessos++;if(state.fixar){const messageId=primeiroMessageId(enviado);if(messageId){try{await enviarTelegram(env.TELEGRAM_TOKEN,"pinChatMessage",{chat_id:id,message_id:messageId,disable_notification:true});fixados++}catch(pinError){errosFixacao++;console.error(`[FIXAR] ${id}`,pinError)}}}}catch(e){erros++;console.error(`[DISPARO] ${id}`,e)}await sleep(1500)}await env.KV_BOT_BANNERS.delete(key);await salvarHistorico(env,{tipo:"manual",sucessos,erros,total:grupos.length,fixar:Boolean(state.fixar),fixados,errosFixacao,data:Date.now()});return atualizarPainel(env,chatId,status.message_id,`✅ <b>DISPARO FINALIZADO</b>\n\n📤 Enviados: <b>${sucessos}</b>\n❌ Erros: <b>${erros}</b>\n👥 Total: <b>${grupos.length}</b>${state.fixar?`\n📌 Fixados: <b>${fixados}</b>\n⚠️ Falhas ao fixar: <b>${errosFixacao}</b>`:""}`,[[{text:"📢 Novo Disparo",callback_data:"menu:disparo"}],[{text:"🏠 Painel",callback_data:"menu:inicio"}]])}
}

async function oferecerFixacao(env,chatId,state,key,messageId){state.step="WAITING_PIN_CHOICE";await apagarMensagem(env,chatId,messageId);state.panelMessageId=null;await salvarEstado(env,key,state);return enviarTelegram(env.TELEGRAM_TOKEN,"sendMessage",{chat_id:chatId,text:"📌 <b>FIXAR PUBLICAÇÃO</b>\n\nDeseja fixar esta postagem nos grupos após o envio?",parse_mode:"HTML",reply_markup:{inline_keyboard:[[{text:"📌 Sim, fixar",callback_data:"disparo:fixar"}],[{text:"➡️ Não fixar",callback_data:"disparo:nao_fixar"}],[{text:"❌ Cancelar",callback_data:"disparo:cancelar"}]]}})}
function primeiroMessageId(enviado){if(Array.isArray(enviado))return enviado.map(x=>x?.message_id).find(Boolean)||null;return enviado?.message_id||null}
export async function mostrarConfirmacao(env,chatId,state){state.userId=String(state.userId||"");if(!state.userId)throw new Error("Admin não identificado.");await apagarPrevia(env,chatId,state);await apagarMensagem(env,chatId,state.confirmMessageId);const markup=state.buttons?{inline_keyboard:state.buttons}:undefined,previa=await enviarConteudo(env,chatId,state,markup);state.previewMessageIds=Array.isArray(previa)?previa.map(m=>m?.message_id).filter(Boolean):[previa?.message_id].filter(Boolean);state.previewMessageId=state.previewMessageIds[0]||null;const grupos=await listarGrupos(env),confirm=await enviarTelegram(env.TELEGRAM_TOKEN,"sendMessage",{chat_id:chatId,text:`👁️ <b>PRÉVIA DO DISPARO</b>\n\n👥 Destinos: <b>${grupos.length} grupos</b>\n📌 Fixar nos grupos: <b>${state.fixar?"SIM":"NÃO"}</b>\n\nConfira a publicação acima. Deseja confirmar o disparo?`,parse_mode:"HTML",reply_markup:{inline_keyboard:[[{text:"✅ Confirmar Disparo",callback_data:"disparo:confirmar"}],[{text:"❌ Cancelar",callback_data:"disparo:cancelar"}]]}});state.confirmMessageId=confirm?.message_id||null;state.step="WAITING_CONFIRMATION";await salvarEstado(env,`state_${state.userId}`,state);return confirm}
async function apagarMensagem(env,chatId,id){if(!id)return;try{await enviarTelegram(env.TELEGRAM_TOKEN,"deleteMessage",{chat_id:chatId,message_id:id})}catch{}}
async function apagarPrevia(env,chatId,state){const ids=state?.previewMessageIds?.length?state.previewMessageIds:state?.previewMessageId?[state.previewMessageId]:[];for(const id of ids)await apagarMensagem(env,chatId,id);if(state?.previewButtonsMessageId)await apagarMensagem(env,chatId,state.previewButtonsMessageId);state.previewMessageIds=[];state.previewMessageId=null;state.previewButtonsMessageId=null}
async function enviarConteudo(env,chatId,state,replyMarkup){const base={chat_id:chatId};if(state.mediaType==="album"){const media=(state.album||[]).map(item=>{const x={type:item.type,media:item.media};if(item.caption){x.caption=item.caption;x.parse_mode="HTML"}return x});if(!media.length)throw new Error("Álbum vazio.");const sent=await enviarTelegram(env.TELEGRAM_TOKEN,"sendMediaGroup",{...base,media});if(replyMarkup){const b=await enviarTelegram(env.TELEGRAM_TOKEN,"sendMessage",{...base,text:"🔗 <b>Links</b>",parse_mode:"HTML",reply_markup:replyMarkup});if(String(chatId)===String(state.userId))state.previewButtonsMessageId=b?.message_id||null}return sent}switch(state.mediaType){case"photo":return enviarTelegram(env.TELEGRAM_TOKEN,"sendPhoto",{...base,photo:state.fileId,caption:state.caption||undefined,parse_mode:"HTML",reply_markup:replyMarkup});case"video":return enviarTelegram(env.TELEGRAM_TOKEN,"sendVideo",{...base,video:state.fileId,caption:state.caption||undefined,parse_mode:"HTML",reply_markup:replyMarkup});case"animation":return enviarTelegram(env.TELEGRAM_TOKEN,"sendAnimation",{...base,animation:state.fileId,caption:state.caption||undefined,parse_mode:"HTML",reply_markup:replyMarkup});case"document":return enviarTelegram(env.TELEGRAM_TOKEN,"sendDocument",{...base,document:state.fileId,caption:state.caption||undefined,parse_mode:"HTML",reply_markup:replyMarkup});case"audio":return enviarTelegram(env.TELEGRAM_TOKEN,"sendAudio",{...base,audio:state.fileId,caption:state.caption||undefined,parse_mode:"HTML",reply_markup:replyMarkup});case"voice":return enviarTelegram(env.TELEGRAM_TOKEN,"sendVoice",{...base,voice:state.fileId,caption:state.caption||undefined,parse_mode:"HTML",reply_markup:replyMarkup});case"video_note":return enviarTelegram(env.TELEGRAM_TOKEN,"sendVideoNote",{...base,video_note:state.fileId});case"sticker":return enviarTelegram(env.TELEGRAM_TOKEN,"sendSticker",{...base,sticker:state.fileId});case"poll":{const p=state.poll||{},x={...base,question:p.question,options:(p.options||[]).map(text=>({text})),is_anonymous:p.is_anonymous,type:p.type||"regular",allows_multiple_answers:p.allows_multiple_answers||false};if(x.type==="quiz"&&Number.isInteger(p.correct_option_id))x.correct_option_id=p.correct_option_id;if(p.explanation)x.explanation=p.explanation;return enviarTelegram(env.TELEGRAM_TOKEN,"sendPoll",x)}case"location":return enviarTelegram(env.TELEGRAM_TOKEN,"sendLocation",{...base,...state.location});case"venue":return enviarTelegram(env.TELEGRAM_TOKEN,"sendVenue",{...base,...state.venue});case"contact":return enviarTelegram(env.TELEGRAM_TOKEN,"sendContact",{...base,...state.contact});case"dice":return enviarTelegram(env.TELEGRAM_TOKEN,"sendDice",{...base,emoji:state.diceEmoji});default:return enviarTelegram(env.TELEGRAM_TOKEN,"sendMessage",{...base,text:state.caption||"",parse_mode:"HTML",reply_markup:replyMarkup})}}
async function salvarEstado(env,key,state){return env.KV_BOT_BANNERS.put(key,JSON.stringify(state),{expirationTtl:3600})}async function salvarHistorico(env,r){let h=[];const raw=await env.KV_BOT_BANNERS.get("historico_envios");if(raw)try{h=JSON.parse(raw)}catch{}h.unshift(r);await env.KV_BOT_BANNERS.put("historico_envios",JSON.stringify(h.slice(0,30)))}function sleep(ms){return new Promise(r=>setTimeout(r,ms))}async function estadoExpirado(env,c){return atualizarPainel(env,c.message.chat.id,c.message.message_id,"⚠️ <b>Essa operação expirou.</b>\n\nInicie um novo disparo.",[[{text:"📢 Novo Disparo",callback_data:"menu:disparo"}]])}
